auteur = "Frederick Douglass"
bloctexte = "justify"
copyright = "CC BY-NC-SA"
couverture = "https://www.gallimardmontreal.com/system/articles/images/grand/9782895960454.jpg"
description = "Description"
edition = "LUX"
format = "portrait"
indentation = "oui"
isbn = ""
licence = "CC BY-NC-SA"
logo = "images/logo.jpg"
marques = "crop"
mention = "LUX"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = "Sous-titre"
titre = "MÃ©moires d'un esclave"
